donjon_rampe_classiques_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("authentification/", include("simple_auth.urls")),
    path("game_data/", include("game_data.urls")),
    path("personnages/", include("characters.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game_data/urls.py
from django.urls import path

from . import views

app_name = "game_data"

urlpatterns = [
    path("sorts_de_mage", views.view_wizard_spells, name="view_wizard_spells"),
    path("sorts_de_clerc", views.view_cleric_spells, name="view_cleric_spells"),
    path("maladresses", views.view_fumbles, name="fumbles"),
    path("maladresses/roll/<str:die_size>", views.roll_fumbles, name="roll_fumbles"),
]

simple_auth/urls.py
from django.urls import path

from .views import register, login_request, logout_request

app_name = "simple_auth"

urlpatterns = [
    path("creer_compte", register, name="register"),
    path("identification", login_request, name="login"),
    path("deconnexion", logout_request, name="logout"),
]

simple_auth/models.py
from django.db import models

# Create your models here.

simple_auth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

simple_auth/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm


def register(request):
    form = NewUserForm()
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("/")
        messages.error(request, "Unsuccessful registration. Invalid information.")

    return render(
        request=request,
        template_name="simple_auth/register.html",
        context={"register_form": form},
    )


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"Bienvenue, {username}.")
                return redirect("index")
            else:
                messages.error(request, "Nom d'utilisateur ou mot de passe invalide.")
        else:
            messages.error(request, "Nom d'utilisateur ou mot de passe invalide.")
    form = AuthenticationForm()
    return render(
        request=request,
        template_name="simple_auth/login.html",
        context={"login_form": form},
    )


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("index")

simple_auth/templates/simple_auth/login.html
{% extends "base.html" %}
{% block content %}

{% load crispy_forms_tags %}

<!--Login-->
<div class="container py-5">
    <h1>Identification</h1>
    <form method="POST">
        {% csrf_token %}
        {{ login_form|crispy }}
        <button class="btn btn-primary" type="submit">S'identifier</button>
    </form>
    <p class="text-center">Vous n’avez pas encore de compte ? <a href="{% url 'simple_auth:register' %}">Créer un compte
            utilisateur gratuit.</a>.</p>
</div>

{% endblock %}

simple_auth/templates/simple_auth/register.html
{% extends "base.html" %}


{% block content %}

{% load crispy_forms_tags %}

<!--Register-->
<div class="container py-5">
    <h1>Créer un compte</h1>
    <form method="POST">
        {% csrf_token %}
        {{ register_form|crispy }}
        <button class="btn btn-primary" type="submit">Créer un compte</button>
    </form>
    <p class="text-center">Si vous avez déjà un compte, <a href="{% url 'simple_auth:login' %}">identifiez-vous par
            là</a> ça vaudra mieux.
    </p>
</div>

{% endblock %}