characters/urls.py
from django.urls import path

from . import views

app_name = "characters"

urlpatterns = [
    path("creer_personnage", views.create_character, name="create_character"),
    path("mes_personnages", views.my_characters.as_view(), name="my_characters"),
    path(
        "mes_personnages/<int:pk>",
        views.character_detail.as_view(),
        name="character_detail",
    ),
]

donjon_rampe_classiques_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("authentification/", include("simple_auth.urls")),
    path("game_data/", include("game_data.urls")),
    path("personnages/", include("characters.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game_data/urls.py
from django.urls import path

from . import views

app_name = "game_data"

urlpatterns = [
    path("sorts_de_mage", views.view_wizard_spells, name="view_wizard_spells"),
    path("sorts_de_clerc", views.view_cleric_spells, name="view_cleric_spells"),
    path("maladresses", views.view_fumbles, name="fumbles"),
    path("maladresses/roll/<str:die_size>", views.roll_fumbles, name="roll_fumbles"),
]

characters/models.py
from django.db import models
from django.conf import settings


# Create your models here.


class Character(models.Model):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    name = models.TextField(max_length=200)
    nickname = models.TextField(max_length=200, null=True, blank=True)
    level = models.SmallIntegerField(default=0, blank=True, null=True)
    classe = models.TextField(max_length=200)
    xp = models.IntegerField()
    title = models.TextField(max_length=200, null=True, blank=True)
    occupation = models.TextField(max_length=200, null=True, blank=True)
    ac = models.SmallIntegerField(default=0, blank=True, null=True)
    hp = models.SmallIntegerField(default=0, blank=True, null=True)
    current_hp = models.SmallIntegerField(default=0, blank=True, null=True)
    speed = models.SmallIntegerField(default=0, blank=True, null=True)
    init = models.SmallIntegerField(default=0, blank=True, null=True)
    strength = models.SmallIntegerField(default=0, blank=True, null=True)
    agility = models.SmallIntegerField(default=0, blank=True, null=True)
    stamina = models.SmallIntegerField(default=0, blank=True, null=True)
    personality = models.SmallIntegerField(default=0, blank=True, null=True)
    intelligence = models.SmallIntegerField(default=0, blank=True, null=True)
    luck = models.SmallIntegerField(default=0, blank=True, null=True)
    reflex = models.SmallIntegerField(default=0, blank=True, null=True)
    fortitude = models.SmallIntegerField(default=0, blank=True, null=True)
    will = models.SmallIntegerField(default=0, blank=True, null=True)
    alignment = models.TextField(max_length=200)
    birthsign = models.TextField(max_length=200)
    birthsign_effect = models.TextField(max_length=200)
    languages = models.TextField(max_length=200, null=True, blank=True)
    patron = models.TextField(max_length=200, null=True, blank=True)
    spells_known = models.TextField(max_length=200, null=True, blank=True)
    inventory = models.TextField(max_length=200, null=True, blank=True)
    proficient_weapons = models.TextField(max_length=200, null=True, blank=True)
    lucky_weapon = models.TextField(max_length=200, null=True, blank=True)
    lucky_spell = models.TextField(max_length=200, null=True, blank=True)
    dead = models.BooleanField()
    curses = models.TextField(max_length=200, null=True, blank=True)
    deity = models.TextField(max_length=200, null=True, blank=True)

characters/forms.py
from django import forms


class CharacterCreationForm(forms.Form):
    name = forms.CharField(
        label="Nom du personnage, laisser vide pour un nom aléatoire, qui sera attribué au niveau 1.",
        max_length=100,
        required=False,
    )

characters/views.py
from random import randint

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.generic import ListView, DetailView

from .models import Character
from .forms import CharacterCreationForm
from donjon_rampe_classiques_django.settings import LOGIN_URL

from .occupations import occupations
from .equipment import equipment
from game_data.utils import threedsix, ability_modifiers
from .birthsigns import birthsigns
from .class_bonuses import (
    level_bonuses,
    mighty_deeds,
    halflin_skills,
    thieves_bonuses,
    thieves_skills,
    luck_die,
)
from .random_names import random_names
from .titles import titles
from .equipment import equipment
from game_data.spells import wizard_spells, cleric_spells


@login_required
def create_character(request):
    """Super dummy view, still todo"""
    if request.method == "POST":
        form = CharacterCreationForm(request.POST)
        if form.is_valid():
            # création du personnage proprement dit
            character = Character()
            character.name = form.cleaned_data["name"] or "Anonyme"
            character.user = request.user
            character.nickname = ""  # TODO add randomtables for nicknames
            character.level = 0
            character.classe = "Paysan"
            character.xp = 0
            character.title = ""  # TODO add randomtables for titles
            occupation_roll = randint(1, 100)
            character.occupation = occupations[occupation_roll][0]
            character.proficient_weapons = occupations[occupation_roll][1]
            character.inventory = f"{occupations[occupation_roll][1]}, {occupations[occupation_roll][2]}, {equipment.get(randint(1,24))[0]}"

            character.strength = threedsix()
            character.agility = threedsix()
            character.stamina = threedsix()
            character.personality = threedsix()
            character.intelligence = threedsix()
            character.luck = threedsix()
            # derived stats
            character.hp = randint(1, 4) + ability_modifiers[character.stamina]
            if character.hp < 1:
                character.hp = 1

            character.current_hp = character.hp
            character.reflex = ability_modifiers[character.agility]
            character.fortitude = ability_modifiers[character.stamina]
            character.will = ability_modifiers[character.personality]
            character.ac = 10 + ability_modifiers[character.agility]

            character.speed = 9
            if "Nain" in character.occupation or "Halfelin" in character.occupation:
                character.speed = 6

            character.init = ability_modifiers[character.agility]
            birth_sign_roll = randint(1, 30)
            character.birthsign = birthsigns[birth_sign_roll][0]
            luck_mod = ability_modifiers[character.luck]
            if luck_mod >= 0:
                character.birthsign_effect = (
                    f"{birthsigns[birth_sign_roll][1]} (+{luck_mod})"
                )
            else:
                character.birthsign_effect = (
                    f"{birthsigns[birth_sign_roll][1]} ({luck_mod})"
                )

            character.languages = "Commun"

            character.patron = ""
            character.deity = ""
            character.spells_known = str([])
            character.dead = False

            # save the char
            character.save()

            # redirect to my characters or character detail
            # add a success message before
            messages.success(request, "Personnage créé.")
            return HttpResponseRedirect(reverse("characters:my_characters"))
    else:
        # build context with empty form
        context = {"form": CharacterCreationForm()}

    return render(request, "characters/create_character.html", context)


class my_characters(LoginRequiredMixin, ListView):
    model = Character
    paginate_by = 10  # if pagination is desired
    template_name = "characters/my_characters.html"
    context_object_name = "characters"

    # redirect_field_name = "personnages/mes_personnages"

    def get_queryset(self):
        return Character.objects.filter(user=self.request.user)


class character_detail(LoginRequiredMixin, DetailView):
    model = Character
    template_name = "characters/character_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["mod"] = ability_modifiers
        context["level_bonuses"] = level_bonuses
        context["mighty_deeds"] = mighty_deeds
        context["titles"] = titles
        context["halflin_skills"] = halflin_skills
        context["thieves_bonuses"] = thieves_bonuses
        context["thieves_skills"] = thieves_skills
        context["luck_die"] = luck_die

        return context

characters/templates/characters/character_detail.html
{% extends "base.html" %}
{% load character_extras %}

{% block title %}
Donjon Rampe Classiques | {{character.name}}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-xs-6">
            <table class="table table-striped" style="width: 400px">
                <tr>
                    <th colspan="2">{{character.name}}</th>
                </tr>
                <tr>
                    <td>Sobriquet</td>
                    <td>{{character.nickname}}</td>
                </tr>
                <tr>
                    <td>Titre</td>
                    <td>{{character.title}}</td>
                </tr>
                <tr>
                    <td>Métier</td>
                    <td>{{character.occupation}}</td>
                </tr>
                <tr>
                    <td>Alignement</td>
                    <td>{{character.alignment}}</td>
                </tr>
                <tr>
                    <td>Signe de naissance</td>
                    <td>{{character.birthsign}}</td>
                </tr>
                <tr>
                    <td>Lancers chanceux</td>
                    <td>{{character.birthsign_effect}}</td>
                </tr>
                <tr>
                    <td>Langages connus</td>
                    <td>{{character.languages}}</td>
                </tr>
            </table>

            <table class="table table-striped" style="width: 400px">
                <tr>
                    <th colspan="2">Inventaire</th>
                </tr>
                <tr>

                    <td colspan="2">{{character.inventory}}</td>
                </tr>

            </table>
            {% if character.lucky_weapon %}
            <table class="table table-striped" style="width: 400px">
                <tr>
                    <th colspan="2">Arme chanceuse</th>
                </tr>
                <tr>

                    <td colspan="2">{{character.lucky_weapon}}</td>
                </tr>

            </table>
            {% endif %}
        </div>
        <div class="col-xs-6"> </div>
        <div class="col-xs-6">
            <table class="table table-striped">
                <tr>
                    <th colspan="2">{{character.classe}}</th>
                </tr>
                <tr>
                    <td>Niveau</td>
                    <td>{{character.level}}</td>
                </tr>
                <tr>
                    <td>❤️</td>
                    <td>{{character.current_hp}} / {{character.hp}}</td>
                </tr>
                <tr>
                    <td>🛡️</td>
                    <td>{{character.ac}}</td>
                </tr>
                <tr>
                    <td>Init</td>
                    {% if character.classe == "Guerrier" %}
                    <td>{{character.init|add:character.level}}</td>
                    {% else %}
                    <td>{{character.init}}</td>
                    {% endif %}
                </tr>
                <tr>
                    <td>Vitesse</td>
                    <td>{{character.speed}}</td>
                </tr>
                <tr>
                    <td>🎲 d’action</td>
                    <td>{{level_bonuses|get_item:character.classe|get_item:character.level|get_item:4}}</td>
                </tr>
                {% if character.classe == "Voleur" %}
                <tr>
                    <td>🎲 de chance</td>
                    <td>{{luck_die|get_item:character.level}}</td>
                </tr>
                {% endif %}

            </table>

        </div>
        <div class="col-xs-6"> </div>
        <div class="col-xs-6">
            <table class="table table-striped" style="width: 250px">
                <tr>
                    <th scope="col">Caractéristique</th>
                    <th scope="col">Valeur</th>
                    <th scope="col">Mod</th>
                </tr>
                <tr>
                    <td>Force</td>
                    <td>{{character.strength}}</td>
                    <td>{{mod|get_item:character.strength}}</td>
                </tr>
                <tr>
                    <td>Agilité</td>
                    <td>{{character.agility}}</td>
                    <td>{{mod|get_item:character.agility}}</td>
                </tr>
                <tr>
                    <td>Endurance</td>
                    <td>{{character.stamina}}</td>
                    <td>{{mod|get_item:character.stamina}}</td>
                </tr>
                <tr>
                    <td>Présence</td>
                    <td>{{character.personality}}</td>
                    <td>{{mod|get_item:character.personality}}</td>
                </tr>
                <tr>
                    <td>Intelligence</td>
                    <td>{{character.intelligence}}</td>
                    <td>{{mod|get_item:character.intelligence}}</td>
                </tr>
                <tr>
                    <td>Chance</td>
                    <td>{{character.luck}}</td>
                    <td>{{mod|get_item:character.luck}}</td>
                </tr>

            </table>
            {% if character.classe == "Halfelin" %}
            <table class="table table-striped" style="width: 250px">
                <tr>
                    <th colspan="2">Compétences</th>
                </tr>
                <tr>
                    <td>Déplacement silencieux</td>
                    <td>+{{halflin_skills|get_item:character.level}}</td>
                </tr>
                <tr>
                    <td>Se cacher dans l’ombre</td>
                    <td>+{{halflin_skills|get_item:character.level}}</td>
                </tr>
            </table>
            {% endif%}
            {% if character.classe == "Voleur" %}
            <table class="table table-striped" style="width: 250px">
                <tr>
                    <th colspan="2">Compétences</th>
                </tr>
                {% for skill in thieves_skills %}
                <tr>
                    <td>{{skill}}</td>
                    <td>{{thieves_bonuses|get_item:character.alignment|get_item:character.level|get_item:skill}}</td>
                </tr>
                {% endfor %}

            </table>
            <ul class="list-group">
                <li class="list-group-item">* Ajouter modificateur d’Agilité
                <li class="list-group-item">† Ajouter modificateur d’Intelligence</li>
                <li class="list-group-item">‡ Ajouter modificateur de Présence</li>
            </ul>
            {% endif %}
            {% if character.classe == "Mage" or character.classe == "Elfe" or character.classe == "Clerc" %}
            <table class="table table-striped" style="width: 250px">
                <tr>
                    <th>Sorts connus</th>

                </tr>
                <tr>
                    <td>{{character.spells_known}}</td>
                </tr>
                {% if character.classe == "Clerc" %}
                <tr>
                    <th>Divinité</th>

                </tr>
                <tr>
                    <td>{{character.deity}}</td>
                </tr>
                {% endif %}

            </table>
            {% endif %}
        </div>
        <div class="col-xs-6"> </div>
        <div class="col-xs-6">
            <table class="table table-striped">
                <tr>
                    <th colspan="2">JdS</th>
                </tr>
                <tr>
                    <td>Réflexes</td>
                    <td>{{mod|get_item:character.agility}} +
                        {{level_bonuses|get_item:character.classe|get_item:character.level|get_item:0}}

                    </td>
                </tr>
                <tr>
                    <td>Vigueur</td>
                    <td>{{mod|get_item:character.stamina}} +
                        {{level_bonuses|get_item:character.classe|get_item:character.level|get_item:1}}
                    </td>
                </tr>
                <tr>
                    <td>Volonté</td>
                    <td>{{mod|get_item:character.personality}} +
                        {{level_bonuses|get_item:character.classe|get_item:character.level|get_item:2}}
                    </td>
                </tr>

                <tr>
                    <th scope="col" colspan="2">Bonus</th>

                </tr>

                <tr>
                    <td>🗡️</td>
                    <td>{{mod|get_item:character.strength}} +
                        {{level_bonuses|get_item:character.classe|get_item:character.level|get_item:3}}
                    </td>
                </tr>
                <tr>
                    <td>🏹</td>
                    <td>{{mod|get_item:character.agility}} +
                        {{level_bonuses|get_item:character.classe|get_item:character.level|get_item:3}}
                    </td>
                </tr>

                {% if character.classe == "Guerrier" or character.classe == "Nain" %}
                <tr>
                    <td>🎲 HF</td>
                    <td>{{mighty_deeds|get_item:character.classe|get_item:character.level}}</td>
                </tr>
                {% endif %}

                {% if character.classe == "Mage" %}
                <tr>
                    <td>🪄</td>

                    <td>{{character.level|add:mod|get_item:character.intelligence}}</td>
                </tr>
                {% elif character.classe == "Clerc" %}
                <tr>
                    <td>🙏</td>
                    <td>{{character.level|add:mod|get_item:character.personality}}</td>
                </tr>
                {% else %}

                {% endif %}

                </tr>
            </table>
            <table class="table table-striped">
                <tr>
                    <th colspan=" 2">Crits</th>
                </tr>
                <tr>
                    <td>Dés</td>
                    <td>{{level_bonuses|get_item:character.classe|get_item:character.level|get_item:5}}</td>
                </tr>
                <tr>
                    <td>Table</td>
                    <td>{{level_bonuses|get_item:character.classe|get_item:character.level|get_item:6}}</td>
                </tr>
            </table>
        </div>
    </div>
</div>


<br>

<a class="btn btn-secondary" role="button" href="#">📝 Modifier</a>

<a class="btn btn-warning" role="button" href="#">💪🏽
    +1 Niveau</a>

{% if character.dead %}

<a class="btn btn-light" role="button" href="#">🙏
    Ressusciter</a>
<a class="btn btn-dark" role="button" href="#">🗑️ Effacer</a>

{% else %}
<a class="btn btn-dark" role="button" href="#">⚰️ Tuer</a>

{% endif %}



{% endblock %}

characters/templates/characters/choose_alignment.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}
Donjon Rampe Classiques | Choisissez l’alignement de {{ char.name }}
{% endblock %}

{% block content %}
<h1>Choisissez l’alignement de {{ char.name }}</h1>
<br>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{url_for('main.index')}}">Taverne</a></li>
        <li class="breadcrumb-item active" aria-current="page">Choisissez l’alignement de {{ char.name }}</li>
    </ol>
</nav>
<br>
{{ render_form(form) }}
{% endblock %}

characters/templates/characters/choose_deity.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}
Donjon Rampe Classiques | Choisissez la Divinité servie par {{ char.name }}
{% endblock %}

{% block content %}
<h1>Choisissez la Divinité servie par {{ char.name }}</h1>
<br>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{url_for('main.index')}}">Taverne</a></li>
        <li class="breadcrumb-item active" aria-current="page">Choisissez la Divinité servie par {{ char.name }}</li>
    </ol>
</nav>
<br>
{{ render_form(form) }}
{% endblock %}

characters/templates/characters/class_selection.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}
Donjon Rampe Classiques | Choisir une classe
{% endblock %}

{% block content %}
<h1>Choisir une classe pour {{character.name}}</h1>
<br>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{url_for('main.index')}}">Taverne</a></li>
        <li class="breadcrumb-item active" aria-current="page">Choisir une classe</li>
    </ol>
</nav>

<div class="container">
    <div class="row">
        <div class="col-sm">
            <table class="table table-striped">
                <tr>
                    <th scope="col">Caractéristique</th>
                    <th scope="col">Valeur</th>
                    <th scope="col">Mod</th>
                </tr>
                <tr>
                    <td>Force</td>
                    <td>{{character.strength}}</td>
                    <td>{{mod[character.strength]}}</td>
                </tr>
                <tr>
                    <td>Agilité</td>
                    <td>{{character.agility}}</td>
                    <td>{{mod[character.agility]}}</td>
                </tr>
                <tr>
                    <td>Endurance</td>
                    <td>{{character.stamina}}</td>
                    <td>{{mod[character.stamina]}}</td>
                </tr>
                <tr>
                    <td>Présence</td>
                    <td>{{character.personality}}</td>
                    <td>{{mod[character.personality]}}</td>
                </tr>
                <tr>
                    <td>Intelligence</td>
                    <td>{{character.intelligence}}</td>
                    <td>{{mod[character.intelligence]}}</td>
                </tr>
                <tr>
                    <td>Chance</td>
                    <td>{{character.luck}}</td>
                    <td>{{mod[character.luck]}}</td>
                </tr>
            </table>
        </div>

        <div class="col-sm">{{ render_form(form) }}</div>


    </div>
</div>

{% endblock %}

characters/templates/characters/create_character.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Donjon Rampe Classiques | Créer un personnage
{% endblock %}

{% block content %}
<h1>Créer un personnage</h1>
<br>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Taverne</a></li>
        <li class="breadcrumb-item active" aria-current="page">Créer un personnage</li>
    </ol>
</nav>
<br>

<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">Créer</button>
</form>

{% endblock %}

characters/templates/characters/edit_character.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}
Donjon Rampe Classiques | Modifier un personnage
{% endblock %}

{% block content %}
<h1>Modifier un personnage</h1>
<br>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{url_for('main.index')}}">Taverne</a></li>
        <li class="breadcrumb-item active" aria-current="page">Modifier un personnage</li>
    </ol>
</nav>
<br>
{{ render_form(form) }}
{% endblock %}

characters/templates/characters/lucky_weapon_selection.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}
Donjon Rampe Classiques | Choisir un type d’arme
{% endblock %}

{% block content %}
<h1>Choisir un type d’armes</h1>
<br>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{url_for('main.index')}}">Taverne</a></li>
        <li class="breadcrumb-item active" aria-current="page">Choisir un type d’arme</li>
    </ol>
</nav>
<br>
{{ render_form(lucky_weapon_form) }}
{% endblock %}

characters/templates/characters/my_characters.html
{% extends "base.html" %}

{% block title %}
Donjon Rampe Classiques | Mes personnages
{% endblock %}

{% block content %}
<h1>Mes Personnages</h1>

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nom</th>
            <th scope="col">Alignement</th>
            <th scope="col">Classe</th>
            <th scope="col">Niveau</th>
            <th scope='col'>PV</th>
            <th scope='col'>Métier</th>
            <th scope="col">Dernière modif</th>
            <th scope="col">Modifier</th>
            <th scope="col">Supprimer</th>
        </tr>
    </thead>
    <tbody>
        {% for char in characters %}
        <tr>
            <th scope="row">{{ loop.index }}</th>
            <td><a href="{% url 'characters:character_detail' char.pk %}">{{char.name}}</a></td>
            <td>{{char.alignment}}</td>
            <td>{{char.class_}}</td>
            <td>{{char.level}}</td>
            <td>{{char.hp}}</td>
            <td>{{char.occupation}}</td>
            <td></td>
            <td><a href="#">📝</a></td>
            <td><a class='danger' href="#">⚰️</a></td>
        </tr>
        {% endfor %}

    </tbody>
</table>

<a class="btn btn-primary" role="button" href="{% url 'characters:create_character' %}">Créer un autre personnage</a>
{% endblock %}