donjon_rampe_classiques_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("authentification/", include("simple_auth.urls")),
    path("game_data/", include("game_data.urls")),
    path("personnages/", include("characters.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game_data/urls.py
from django.urls import path

from . import views

app_name = "game_data"

urlpatterns = [
    path("sorts_de_mage", views.view_wizard_spells, name="view_wizard_spells"),
    path("sorts_de_clerc", views.view_cleric_spells, name="view_cleric_spells"),
    path("maladresses", views.view_fumbles, name="fumbles"),
    path("maladresses/roll/<str:die_size>", views.roll_fumbles, name="roll_fumbles"),
]

game_data/views.py
from django.shortcuts import render
from django.contrib import messages

from .spells import wizard_spells, cleric_spells
from .fumbles import fumbles
from utils.roll import roll

# Create your views here.


def view_wizard_spells(request):
    context = {"spells": wizard_spells}

    return render(
        request, template_name="game_data/view_wizard_spells.html", context=context
    )


def view_cleric_spells(request):
    context = {"spells": cleric_spells}

    return render(
        request, template_name="game_data/view_cleric_spells.html", context=context
    )


def view_fumbles(request):
    context = {"fumbles": fumbles}
    return render(request, "game_data/fumbles.html", context)


def roll_fumbles(request, die_size):
    result = roll(die_size)
    messages.success(
        request,
        f"Votre résultat naturel : {result}. Ajustez-le en soustrayant votre bonus de chance.",
    )
    return view_fumbles(request)

game_data/templates/game_data/equipment.html
{% extends "base.html" %}

{% block title %}
Donjon Rampe Classiques | Maladresses
{% endblock %}

{% block content %}
<h1>Équipement</h1>

<p>Lors de la création de personnage, lancez un d24 sur cette table et ajoutez l’objet à votre inventaire.
    <a class="btn btn-primary" role="button" href="{{url_for('main.equipment_roll')}}">
        🎲 d24</a>
</p>
<p>NB : le générateur de personnages de ce site ajoute déjà un objet de cette liste à l’inventaire de tout personnage
    créé.</p>

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th scope="col">d24</th>
            <th scope="col">Objet</th>
            <th scope="col">Coût</th>

        </tr>
    </thead>
    <tbody>
        {% for die_value, (object, cost) in equipment.items() %}
        <tr>
            <td>{{die_value}}</td>
            <td>{{object}}</td>
            <td>{{cost}}</td>
        </tr>
        {% endfor %}

    </tbody>
</table>


{% endblock %}

game_data/templates/game_data/fumbles.html
{% extends "base.html" %}

{% block title %}
Donjon Rampe Classiques | Maladresses
{% endblock %}

{% block content %}
<h1>Maladresses</h1>

<p>Selon votre armure, lancez le dé adéquat sur cette table.</p>


<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th scope="col">Armure</th>
            <th scope="col">Dé à lancer</th>

        </tr>
    </thead>
    <tbody>

        <tr>
            <td>Sans armure</td>
            <td><a class="btn btn-primary" role="button" href="{% url 'game_data:roll_fumbles' 'd4' %}">lancer un
                    d4</a></td>
        </tr>
        <tr>
            <td>Armure matelassée, de cuir, de cuir clouté</td>
            <td><a class="btn btn-primary" role="button" href="{% url 'game_data:roll_fumbles' 'd8' %}">lancer un D8</a>
            </td>
        </tr>
        <tr>
            <td>Armure de peau, d'écailles, Côte de mailles</td>
            <td><a class="btn btn-primary" role="button" href="{% url 'game_data:roll_fumbles' 'd12' %}">lancer un
                    D12</a>
            </td>
        </tr>
        <tr>
            <td>Clibanion, Armure de Plates, Harnois</td>
            <td><a class="btn btn-primary" role="button" href="{% url 'game_data:roll_fumbles' 'd16' %}">lancer un
                    D16</a>
            </td>
        </tr>

    </tbody>
</table>


<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th scope="col">Résultat</th>
            <th scope="col">Effet</th>

        </tr>
    </thead>
    <tbody>
        {% for result, effect in fumbles.items %}
        <tr>
            <td>{{result}}</td>
            <td>{{effect}}</td>
        </tr>
        {% endfor %}

    </tbody>
</table>


{% endblock %}

game_data/templates/game_data/view_cleric_spells.html
{% extends "base.html" %}

{% block title %}
Donjon Rampe Classiques | Sorts de Clerc
{% endblock %}

{% block content %}
<h1>Sorts de Clerc</h1>

{% for level, spell_list in spells.items %}
<ul>
    <li> Niveau {{ level }} : </li>
    <ul>
        {% for sp in spell_list %}
        <li> {{ sp }} </li>
        {% endfor %}
    </ul>
</ul>
{% endfor %}

{% endblock %}

game_data/templates/game_data/view_wizard_spells.html
{% extends "base.html" %}

{% block title %}
Donjon Rampe Classiques | Sorts de Mage
{% endblock %}

{% block content %}
<h1>Sorts de Mage</h1>

{% for level, spell_list in spells.items %}
<ul>
    <li> Niveau {{ level }} : </li>
    <ul>
        {% for sp in spell_list %}
        <li> {{ sp }} </li>
        {% endfor %}
    </ul>
</ul>
{% endfor %}

{% endblock %}