characters/urls.py
from django.urls import path

from . import views

app_name = "characters"

urlpatterns = [
    path("creer_personnage", views.create_character, name="create_character"),
    path("mes_personnages", views.my_characters.as_view(), name="my_characters"),
    path(
        "mes_personnages/<int:pk>",
        views.character_detail.as_view(),
        name="character_detail",
    ),
]

donjon_rampe_classiques_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("authentification/", include("simple_auth.urls")),
    path("game_data/", include("game_data.urls")),
    path("personnages/", include("characters.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game_data/urls.py
from django.urls import path

from . import views

app_name = "game_data"

urlpatterns = [
    path("sorts_de_mage", views.view_wizard_spells, name="view_wizard_spells"),
    path("sorts_de_clerc", views.view_cleric_spells, name="view_cleric_spells"),
    path("maladresses", views.view_fumbles, name="fumbles"),
    path("maladresses/roll/<str:die_size>", views.roll_fumbles, name="roll_fumbles"),
]

simple_auth/urls.py
from django.urls import path

from .views import register, login_request, logout_request

app_name = "simple_auth"

urlpatterns = [
    path("creer_compte", register, name="register"),
    path("identification", login_request, name="login"),
    path("deconnexion", logout_request, name="logout"),
]

templates/base.html
<!doctype html>
<html lang="en">


<head>

    <!-- boostrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %}Donjon Rampe Classiques{% endblock %}</title>
    <link rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🏰</text></svg>">

</head>

<body>
    <!-- Nav bar-->
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">🏰 Donjon Rampe Classiques</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Personnages</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                            <a class="dropdown-item" href="{% url 'characters:create_character' %}">Créer un
                                personnage</a>
                            <a class="dropdown-item" href="{% url 'characters:my_characters' %}">Mes personnages</a>
                            <a class="dropdown-item" href="#">Cimetière</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">🛒 Équipement</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">🎒 Objets</a>
                            <a class="dropdown-item disabled" href="#">🍵 Poisons</a>

                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">🔮 Magie</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                            <a class="dropdown-item" href="{% url 'game_data:view_wizard_spells' %}">🧙 Sorts</a>
                            <a class="dropdown-item" href="{% url 'game_data:view_cleric_spells' %}">🙏 Prières</a>
                            <a class="dropdown-item disabled" href="#">🎭 Patrons</a>
                            <a class="dropdown-item disabled" href="#">🕍 Dieux</a>
                            <a class="dropdown-item disabled" href="#">🧟 Malédictions</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">🎲 Tables critiques</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item disabled" href="#">💥 Critiques</a>
                            <a class="dropdown-item" href="{% url 'game_data:fumbles' %}">🏈 Maladresses</a>
                        </div>

                    </li>
                </ul>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Modifier mon compte</a>

                            <div class=" dropdown-divider">
                            </div>
                            <a class="dropdown-item" href="{% url 'simple_auth:logout' %}">Déconnexion</a>
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'simple_auth:login'%}">S’identifier / Créer un compte <span
                                class="sr-only">(current)</span></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>

    </nav>
    <!--messages-->

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    {% endblock %}
    <div class="container div-1">

        <div id="content">
            {% block content %}{% endblock %}
            <br><br>
        </div>
    </div>
    <!-- Jquery and Popper-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>


    <!-- Bootstrap JS -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block title %}
Donjon Rampe Classiques
{% endblock %}

{% block content %}
<h1>Bonjour
    {% if current_user.is_authenticated %}
    {{ current_user.username }}
    {% else %}
    l'ami…
    {% endif %}!
</h1>

<br>

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h2 class="display-4">Bienvenue sur Donjon Rampe Classiques</h2>
        <p class="lead">Créez vos héros et votre bande d'aventuriers pour le jeu de rôle Dungeon Crawl Classics de
            <a href="https://goodman-games.com/dungeon-crawl-classics-rpg/">Goodman Games</a>, version française publiée
            par <a href="https://akileos.fr/boutique/index.php?id_category=16&controller=category"
                target="_blank">Akileos</a>.
        </p>
    </div>
</div>

{% endblock %}

templates/my_profile.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}
Donjon Rampe Classiques | Modifier mon compte
{% endblock %}

{% block content %}
<h1>Modifier mon compte</h1>
<br></br>


{{ render_form(profileform) }}
{% endblock %}